steps:
- name: gcr.io/cloud-builders/docker
  id: Build image
  args:
  - build
  - -t
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$BUILD_ID
  - .

- name: gcr.io/cloud-builders/docker
  id: Push image
  args:
  - push
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$BUILD_ID

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy to Cloud Run
  entrypoint: gcloud
  args:
  - run
  - deploy
  - ${_SERVICE}
  - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$BUILD_ID
  - --region=${_REGION}
  - --platform=managed
  - --allow-unauthenticated
  - --port=8080
  - --memory=256Mi
  - --cpu=1
  - --max-instances=3

substitutions:
  _REGION: us-central1
  _REPO: organograma
  _SERVICE: organograma-web

images:
- ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$BUILD_ID

options:
  logging: CLOUD_LOGGING_ONLY
